version: "3.4"

# ----------------------------------------------------------------------------------------------------------------------
#
#   Service
#
# ----------------------------------------------------------------------------------------------------------------------
services:
  app:
    hostname: container-app
    container_name: emlab-tutorial-client
    image: emlab/tutorial/fetch:noetic
    volumes:
      # GUI
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ${XDG_RUNTIME_DIR}/gdm/Xauthority
        target: ${XDG_RUNTIME_DIR}/gdm/Xauthority
      # catkin_ws
      - type: bind
        source: ../catkin_ws/src
        target: /home/docker/catkin_ws/src
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
      # ID.
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
      # PulseAudio.
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
    privileged: true
    tty: true
    ipc: host