version: "3.4"

# ----------------------------------------------------------------------------------------------------------------------
#
#   Service
#
# ----------------------------------------------------------------------------------------------------------------------
services:
  builder:
    image: emlab/tutorial/fetch:noetic
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=nvidia/cudagl:11.3.1-devel-ubuntu20.04