version: "3.4"

services:
  ros:
    hostname: ${HOSTNAME}
    image: emlab_ros_tutorial:2022
    container_name: noetic-tutorial
    build:
      context: ./
      args:
        - FROM_IMAGE=nvidia/cudagl:11.3.1-devel-ubuntu20.04
    volumes:
      # Grant display access to X Server.
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      # Grant audio access to PulseAudio.
      - type: bind
        source: ${XDG_RUNTIME_DIR}/pulse/native
        target: ${XDG_RUNTIME_DIR}/pulse/native
      - type: bind
        source: ${XDG_RUNTIME_DIR}/gdm/Xauthority
        target: ${XDG_RUNTIME_DIR}/gdm/Xauthority
      # Init environement variables
#      - type: bind
#        source: ../catkin_ws/src
#        target: /home/docker/catkin_ws/src
#      - type: bind
#        source: ../catkin_ws/dist-packages
#        target: /home/docker/catkin_ws/dist-packages
    environment:
      # Display X Server GUIs.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # PulseAudio.
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      # ID.
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
      - USER_NAME=${USER_NAME}
    network_mode: host
    privileged: true
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
