version: "3.4"

# ----------------------------------------------------------------------------------------------------------------------
#
#   Service
#
# ----------------------------------------------------------------------------------------------------------------------
services:
  app:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]